name: learn-github-actions
on:
  pull_request_target:
    types: [opened]
  workflow_dispatch:
  push:

jobs:
  notify:
    name: Notify Created PR
    runs-on: ubuntu-latest
    steps:
      - name: "Send Notification"
        run: |
          cat "$GITHUB_EVENT_PATH" | jq '.text = "<!subteam^idhub>\n" + .pull_request.title + "PRです。\nご確認とマージお願いします。" + .pull_request.html_url | {
            text: .text
          }' | curl -H 'Content-Type: application/json' -d @- ${{ secrets.SLACK_WEBHOOK }}
