name: learn-github-actions
on: [pull_request]

jobs:
  notify:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
      - name: "Send Notification"
        run: |
          cat "$GITHUB_EVENT_PATH" | jq '{
            attachments: [{
              pretext: "<!subteam^idhub>",
              color: "good",
              title: .pull_request.title,
              title_link: .pull_request.html_url
            }]
          }' | curl -H 'Content-Type: application/json' -d @- https://hooks.slack.com/services/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
