name: learn-github-actions
on:
  pull_request_target:
    types: [opened]

jobs:
  notify:
    name: Notify Created PR
    runs-on: ubuntu-latest
    steps:
      - name: "Send Notification"
        run: |
          cat "$GITHUB_EVENT_PATH" | jq '.title = .pull_request.title + "PRです。\nご確認とマージお願いします。" | {
            attachments: [{
              pretext: "<!subteam^idhub>",
              color: "good",
              title: .title,
              title_link: .pull_request.html_url
            }]
          }' | curl -H 'Content-Type: application/json' -d @- ${{ secrets.SLACK_WEBHOOK }}
